import type { SponsorPageContent, Vertical } from "./types";

/*
 * ascentforsponsors.com — investor acquisition for real estate syndicators
 * and private real estate fund sponsors raising under Reg D Rule 506(c).
 *
 * Served at /sponsors and, via the host rewrite in next.config.ts, as the
 * ROOT of ascentforsponsors.com. Rendered by the dark sponsor template
 * (src/components/sponsor/SponsorPage.tsx), which reads this `Vertical`
 * for the gate, booking, benchmarks, boundaries, fit, FAQ and footer, and
 * the `sponsorsPage` export below for the sections only that template has.
 * `business.url` and `canonicalUrl` point at that domain, so the canonical,
 * JSON-LD, robots and sitemap all describe the sponsor site whichever host
 * actually served the request.
 *
 * Sources: the Ascent business plan (RE sponsors, second edition, Sept
 * 2026), the Brand Style Guide v2.0, Delivery Boundaries v2.0, and the
 * metrics ontology. Several conventions here are compliance positions, not
 * style choices — keep them when editing:
 *
 *   - "appointment held", never set / booked / scheduled.
 *   - "investor lead", never prospect or qualified investor.
 *   - "flat monthly fee" — nothing tied to capital raised, investors
 *     acquired, or appointments held. The one guarantee on this page is the
 *     proposal's own: a minimum of appointments HELD in 90 days or the fee
 *     stops until it's met — never a result, never anything about capital.
 *     (The brand guide's default is no guarantee in collateral; the owner
 *     chose to publish this one, in the proposal's exact terms.)
 *   - "sponsor" / "issuer"; the investors are never Ascent's.
 *   - Live, human, scripted calls only. The automated channels are texts
 *     and emails — write the channel out; never "automated calls".
 *   - No pricing published. It is quoted in writing after the scoping call
 *     (`pricing: null`, `expectations` in its place).
 *   - Every number on the page traces to the metrics ontology or to a
 *     published, attributed category benchmark. No Ascent results are
 *     published until a sponsor agrees to a named, written case study.
 */
/*
 * The sponsor page's content date — the sitemap lastmod and the WebPage
 * dateModified. Bump it when the page's copy changes; a build date would
 * tell crawlers the page changed on every deploy, which it does not.
 */
export const SPONSOR_PAGE_UPDATED = "2026-09-09";

const sponsors: Vertical = {
  slug: "sponsors",
  path: "/sponsors",
  canonicalUrl: "https://ascentforsponsors.com",

  business: {
    name: "Ascent",
    url: "https://ascentforsponsors.com",
    city: "Oklahoma City",
    region: "OK",
    // Delivery is entirely remote; the firm sells nationally.
    areaServed: "United States",
    // The registered street address. Rendered in the footer and in the
    // contact sections of /privacy and /terms, and in the JSON-LD address.
    street: "1424 Highland Park Blvd",
    postalCode: "73114",
    phone: "580-304-8470",
    // The sponsor domain's own mailbox — footer, /privacy and JSON-LD pick
    // it up. It must exist and be monitored; nothing on the site sends to it.
    email: "info@ascentforsponsors.com",
    // Entity facts for the Organization JSON-LD and the guide bylines.
    legalName: "Ascent Client Acquisition Systems LLC",
    founder: { name: "Caleb Free", title: "Founder" },
    // The firm's own profile URLs (LinkedIn company page, etc.). Empty until
    // the owner supplies them — never guess a URL here.
    sameAs: [],
  },

  // The call this vertical books, as the transactional SMS consent
  // sentence names it (content/compliance.ts).
  smsCallName: "scoping call",

  seo: {
    // A vertical owns its whole title (src/lib/metadata.ts sets it
    // absolute), so the brand suffix is written out here. Leads with the
    // two names the buyer actually searches — syndicator and 506(c)
    // sponsor.
    title: "Investor Acquisition for Real Estate Syndicators & 506(c) Sponsors | Ascent",
    description:
      "Flat-fee investor acquisition for real estate syndicators and 506(c) fund sponsors: counsel-approved paid media, instant lead response, and a live scripted setter who turns accredited-investor leads into meetings that are held.",
    // The v3 lockup on ink, generated by scripts/build-v3-assets.mjs.
    ogImage: "/og-sponsors.png",
  },

  header: {
    cta: "Book a scoping call",
  },

  hero: {
    // The one eyebrow the brand guide mandates. "(c)" survives the CSS
    // uppercase via EyebrowText — it is a rule citation, not a letter.
    eyebrow: "INVESTOR ACQUISITION FOR 506(c) SPONSORS",
    h1: "Investor meetings held, not just investor leads.",
    // The orange lands on the promise, never on the problem.
    h1Highlight: "Investor meetings held",
    sub: "Roughly two percent of investor leads become investors. Most of the rest were never called, or were called days later by someone reading no script — and you paid to generate every one. Ascent works the other ninety-eight: a live setter calling as you, inside a structure your securities counsel approved in writing.",
    closingLine: "You run the investor conversation. We run everything before it.",
    cta: "See if you qualify",
    secondaryCta: null,
    // Practice claims only — things a sponsor or their counsel can check.
    chips: [
      "Every setter call recorded",
      "Counsel-approved script",
      "Cost per appointment held",
    ],
    // Illustrative week — generic labels only, never names, funds, dollar
    // figures, or counts presented as results.
    calendar: {
      title: "Your calendar — this week",
      days: ["Mon", "Tue", "Wed", "Thu"],
      times: ["9:00", "11:00", "1:00", "3:00"],
      blocks: [
        { day: 0, row: 1, label: "Investor meeting", time: "11:00", kind: "booked" },
        { day: 1, row: 0, label: "Setter call", time: "9:30 · REC", kind: "call" },
        { day: 1, row: 2, label: "Investor meeting", time: "1:00", kind: "booked" },
        { day: 2, row: 1, label: "Investor meeting", time: "11:30", kind: "booked" },
        { day: 2, row: 3, label: "Setter call", time: "3:15 · REC", kind: "call" },
        { day: 3, row: 0, label: "Investor meeting", time: "9:00", kind: "booked" },
        { day: 3, row: 2, label: "Investor meeting", time: "1:30", kind: "booked" },
      ],
      caption:
        "Investor leads called back by a live setter, as you, on a script your counsel approved — then confirmed onto your calendar.",
    },
    microcopy: "30 minutes. No cost, no obligation. Counsel welcome.",
  },

  /*
   * Cost per appointment held — the primary metric — from the sponsor's own
   * assumptions. Deliberately NOT a revenue or capital-raised projection:
   * that would be a performance claim this page must not make.
   */
  calculator: {
    kind: "appointments",
    fields: {
      mediaBudget: {
        label: "Monthly media budget",
        min: 5000,
        max: 100000,
        step: 1000,
        defaultValue: 15000,
        unit: "$",
        numberInput: true,
      },
      costPerLead: {
        label: "Cost per investor lead",
        min: 25,
        max: 500,
        step: 5,
        defaultValue: 75,
        unit: "$",
        numberInput: true,
      },
      contactRate: {
        label: "Leads that get a connected touch",
        min: 10,
        max: 90,
        step: 1,
        defaultValue: 40,
        unit: "%",
        numberInput: false,
      },
      heldRate: {
        label: "Contacted leads whose meeting is held",
        min: 5,
        max: 60,
        step: 1,
        defaultValue: 20,
        unit: "%",
        numberInput: false,
      },
    },
    outputs: {
      leads: "Investor leads / month",
      costPerHeld: "Cost per appointment held",
      held: "Appointments held / month",
      uncontacted: "Leads never contacted / month",
    },
    assumptionLine:
      "Arithmetic on your assumptions, not a projection: budget ÷ cost per lead, × the share reached, × the share whose meeting is held. Cost per lead defaults to the published Meta benchmark for this category; the two rates are yours to set. Media spend only — the fee never enters a cost-per number unless a report says fully loaded.",
  },

  calculatorSection: {
    eyebrow: "RUN YOUR RAISE'S NUMBERS",
    h2: "What does one investor appointment held cost you?",
    sub: "Set your media budget and cost per lead, then the two rates nobody tracks — how many leads get a connected touch, and how many of those turn into a meeting that is actually held. That last number is the one we manage to.",
  },

  problem: {
    eyebrow: "THE ACTUAL PROBLEM",
    h2: "Your raise isn't short on leads. It's short on the first ninety seconds after one arrives.",
    paragraphs: [
      "An accredited investor fills out the form on your ad. They get an email autoresponder. A human calls them three days later, if at all, working from no script, on a line nobody records. Your agency reports the lead as delivered — and by its definition, it was.",
      "Every agency in this category sells the top of that funnel: targeting, landing pages, creative, nurture. Their published service lists contain no live calling, no appointment setting, and no investor-relations staffing. The published lead-to-investor rate is about two percent, and nobody in the chain is paid to move it.",
      "Capital-raise marketing sits in the gap between two professions. Marketing agencies write manufactured urgency into what is legally a securities communication. Securities lawyers know the rules and cannot run a media buy. Neither one measures speed to lead, contact rate, or whether a meeting that was booked was ever held.",
      "Ascent is built to sit in that gap on purpose. It runs the media, staffs the phone with a live setter calling as you, instruments every touch, and does all of it inside a structure your securities counsel has approved in writing before anything publishes.",
    ],
  },

  /*
   * The diagram. Stage copy describes what the system DOES — never counts,
   * rates, or dollars. Badges are statements of how the firm operates.
   */
  // Rendered as the numbered process in `sponsorsPage` instead.
  systemFlow: null,

  // Rendered as the feature grid in `sponsorsPage` instead.
  services: null,

  // Folded into services.ownerCard on this page.
  howItWorks: null,

  /*
   * Required by the Vertical interface and used by the light template's
   * ProofSection — the dark sponsor template does not render it. The 2%
   * figure it carries is attributed in `sponsorsPage.problems.note`, where
   * that number now appears on the page.
   */
  proof: {
    srHeading: "The category's published numbers",
    framingLine:
      "The category publishes its own failure rate. These are the published benchmarks for 506(c) investor acquisition — not Ascent's numbers, and the reason the setter exists.",
    stats: [
      { number: "~2%", label: "of investor leads become investors" },
      {
        number: "$50–$100",
        label: "cost per investor lead on Meta; LinkedIn runs roughly five times that",
      },
      {
        number: "$3.5K–4.5K",
        label: "cost per funded investor, within 90 days of first contact",
      },
    ],
    // A published source, not a client result. Ascent publishes none of its
    // own sponsor numbers until a sponsor agrees to a named, written case
    // study — never fill this with an unattributed figure.
    attributionLine:
      "Published category benchmarks for real estate 506(c) investor marketing (GowerCrowd). Ascent reports its own numbers to each sponsor weekly and publishes none of them without a named, written case study.",
    reportCard: null,
    screenshots: [],
  },

  /*
   * Practice claims only — what a sponsor or their counsel can check.
   * Numbers live in `proof`, attributed.
   */
  // Folded into the process and feature grid in `sponsorsPage`.
  transparency: null,

  boundaries: {
    eyebrow: "WHAT WE NEVER DO",
    h2: "The terms on which Ascent is not a broker.",
    intro:
      "On a capital-raise engagement these are not scope decisions. They are absolute, they are in the contract, and they are the reason your securities counsel can approve the structure without redrafting it.",
    items: [
      {
        title: "Flat monthly fee. Nothing else.",
        body: "Nothing tied to capital raised, investors acquired, or appointments held. Never traded for upside, at any performance level. The CRM has no field for it, so it cannot be argued about.",
      },
      {
        title: "The setter never discusses the offering.",
        body: "No returns, valuation, merits, timing, or terms. Every touch is logistical. A breach is a stop-work event, not a coaching moment.",
      },
      {
        title: "Verification stays with you, permanently.",
        body: "Ascent never asks about, assesses, or verifies accredited-investor status. Ascent never touches funds and never gives investment advice.",
      },
      {
        title: "Nothing publishes and nobody dials without counsel approval.",
        body: "If an approval lapses, calling stops the same day, in writing. If your counsel raises a question, the lane pauses until it is answered.",
      },
      {
        title: "Live, human, scripted calls only.",
        body: "No prerecorded audio, no artificial voice, no robo-dialing. Only inbound leads you generated — never a purchased list, never a scraped number, never your old database without scoping it first.",
      },
      {
        title: "Everything built belongs to you.",
        body: "The phone number is registered to you. The recordings are yours. The investor list is yours at the end, whether or not you stay.",
      },
    ],
    closing:
      "Your counsel receives one complete package — the script, the legends, the approval workflow, and the express no-transaction-based-compensation clause — with one review deadline. The point is to remove work from their desk, not to argue with it.",
  },

  fit: {
    eyebrow: "WHO THIS IS FOR",
    h2: "Built for a narrow client. Deliberately.",
    forYouHeading: "This is for you if",
    forYou: [
      "You are a U.S. real estate sponsor — multifamily, industrial, self-storage, build-to-rent, opportunity zone, or real estate credit.",
      "You have a live Rule 506(c) offering of $10 million or more, or an evergreen vehicle that raises continuously.",
      "Securities counsel is already engaged, with a named approver who can turn a review in three business days.",
      "You can fund a media budget of at least $15,000 a month, paid by you to the platform on your own account.",
      "You have raised before, and relationship-based raising has stopped filling the deal.",
    ],
    notForYouHeading: "This is not for you if",
    notForYou: [
      "The offering is 506(b). General solicitation is prohibited there, and no vendor can change that.",
      "There is no securities counsel. The compliance gate never clears without one.",
      "It is a single-asset raise under $10 million with no fund program behind it. The arithmetic doesn't fund a stable campaign plus the fee.",
      "You are mid-capital-call, or distributions are paused.",
      "You want compensation tied to capital raised. That is the one term Ascent will never sign.",
    ],
    note: "Close but not there? Book the call anyway and say so. The answer might be “not yet,” and it will be a useful one.",
  },

  // No published pricing on this page — quoted in writing after the call.
  pricing: null,

  // Folded into the process steps in `sponsorsPage`.
  expectations: null,

  // No performance guarantee ever attaches to a regulated raise.
  guarantees: null,

  /*
   * Every answer restates facts already published on this page — the
   * boundaries, the owner-card steps, the expectations. Nothing new is
   * claimed here; if a fact changes above, change it here too.
   */
  faq: {
    eyebrow: "FREQUENTLY ASKED QUESTIONS",
    h2: "What sponsors and their counsel ask first.",
    items: [
      {
        q: "What is investor acquisition for a 506(c) raise?",
        a: "Generating accredited-investor leads for a syndication or fund that is permitted to advertise under Rule 506(c), and then working those leads until a meeting with the sponsor is actually held. Ascent runs the whole path — counsel-approved media, instrumented response, and a live setter — and reports it as cost per appointment held.",
      },
      {
        q: "How much should we budget?",
        a: "Two lines. Media, which you pay to the platform on your own account — $15,000 a month is the floor at which a campaign holds a stable footing, and published guidance for this category puts total marketing at roughly three to four percent of the raise. And Ascent's flat monthly fee, which scales with media under management and is quoted in writing after the scoping call.",
      },
      {
        q: "How long until the lane is live?",
        a: "Fourteen days from account access and counsel's approvals. The compliance gate runs first and in parallel with scoping; the build clock starts when the gate closes, not before. The first weekly report follows the first full week live.",
      },
      {
        q: "What results can we expect?",
        a: "Ascent publishes no client figures without a named, written case study, and nothing on this site projects capital raised. What you get in writing is a minimum number of investor appointments held in the first ninety days, set in your proposal from your own media budget and history — and if it's missed, Ascent keeps working at no fee until it's met. Plus the reporting: median speed to first human touch, contact rate by response bucket, set-to-held rate, and cost per appointment held, every week from the first one.",
      },
      {
        q: "Is Ascent a broker-dealer, finder, or placement agent?",
        a: "No. Compensation is a flat monthly fee — nothing tied to capital raised, investors acquired, or appointments held, at any performance level. Ascent never touches funds, never verifies accredited-investor status, and never gives investment advice. Those terms are in the contract, not in a policy.",
      },
      {
        q: "What does the setter actually say to an investor lead?",
        a: "Logistics only: confirming the lead asked to hear from you, and getting a meeting onto your calendar. The setter never discusses returns, valuation, merits, timing, or terms — a script your counsel approved holds that line, and every call is recorded so counsel can check it.",
      },
      {
        q: "Who verifies accredited-investor status?",
        a: "You do, permanently. Ascent never asks about, assesses, or verifies it, and the CRM Ascent operates has no field for it.",
      },
      {
        q: "What does it cost?",
        a: "A flat monthly fee that scales with media under management, quoted in writing after the scoping call — once we have read your numbers, not before. Media spend is billed by the platform directly to you, on your own account; Ascent never holds, advances, or marks it up.",
      },
      {
        q: "What if our counsel has questions or an approval lapses?",
        a: "Counsel gets one complete package — the script, the legends, the approval workflow, and the express no-transaction-based-compensation clause — with one review deadline of three business days. Nothing publishes and nobody dials without approval, and if an approval lapses, calling stops the same day, in writing. Bring counsel to the scoping call.",
      },
      {
        q: "Do you work with 506(b) offerings?",
        a: "No. General solicitation is prohibited under 506(b), and no vendor can change that. If you are filing a 506(c) offering in the next ninety days, the scoping call is still the right first step.",
      },
      {
        q: "What do we keep if we leave?",
        a: "Everything built: the phone number registered to you, every call recording, the investor list, and the setter scripts. Nothing is held hostage to the engagement.",
      },
    ],
  },

  booking: {
    eyebrow: "BOOK A SCOPING CALL",
    h2: "Find out where your last raise's leads went.",
    body: "Thirty minutes. Bring the numbers from your last raise — media spent, leads generated, meetings that actually happened. We'll tell you, in dollars, what the gap between the leads you paid for and the appointments you held is costing you, and whether this structure will clear your counsel. If it doesn't fit, we'll say so on the call.",
    // A dedicated Calendly event for sponsors, separate from the brand
    // page's strategy call, so bookings from this domain are their own
    // event type. The event MUST exist in Calendly under exactly this slug
    // (caleb-ascentcas → "Scoping call", URL slug "scoping-call", 30 min)
    // before the domain goes live — a qualified sponsor is shown this embed,
    // and a missing event renders Calendly's not-found page in its place.
    // Set-up steps are in CONNECT-ASCENTFORSPONSORS.md.
    schedulingLink:
      "https://calendly.com/caleb-ascentcas/scoping-call?hide_gdpr_banner=1&embed_domain=ascentforsponsors.com&embed_type=Inline",
    // Legacy form labels — the gate below is the live path.
    form: {
      nameLabel: "Name",
      companyLabel: "Sponsor or fund",
      phoneLabel: "Phone",
      emailLabel: "Email",
      estimatesSelectLabel: "Offering status",
      estimatesSelectOptions: [
        "Open 506(c) raise, advertising now",
        "Open 506(c) raise, not yet advertising",
        "Filing in the next 90 days",
        "506(b), or not sure",
      ],
      tradeField: null,
      submitLabel: "Request a call",
      submittingLabel: "Sending…",
    },
  },

  // The ICP gate in front of the scheduler. A prospect qualifies only when
  // EVERY chosen option carries `qualifies: true`. The thresholds are the
  // ideal-client definition from the business plan: a live 506(c) (or
  // Reg A+) offering of $10M+ or an evergreen vehicle, counsel engaged, a
  // media budget of $15K/month or more, a track record, and a buyer who
  // can actually say yes — the sponsor principal, head of IR, or the
  // compliance owner.
  qualification: {
    nameLabel: "Name",
    companyLabel: "Sponsor or fund",
    phoneLabel: "Phone",
    emailLabel: "Email",
    questions: [
      {
        key: "exemption",
        label: "Which exemption is the offering under?",
        options: [
          { label: "Rule 506(c) — we can advertise", qualifies: true },
          { label: "Regulation A+", qualifies: true },
          { label: "Rule 506(b)", qualifies: false },
          { label: "Not sure yet", qualifies: false },
        ],
      },
      {
        key: "raiseSize",
        label: "How large is the offering?",
        options: [
          { label: "Under $10 million", qualifies: false },
          { label: "$10–$25 million", qualifies: true },
          { label: "$25–$50 million", qualifies: true },
          { label: "More than $50 million", qualifies: true },
          { label: "Evergreen or continuously offered", qualifies: true },
        ],
      },
      {
        key: "counsel",
        label: "Is securities counsel engaged on this offering?",
        options: [
          { label: "Yes — engaged", qualifies: true },
          { label: "Not yet", qualifies: false },
        ],
      },
      {
        key: "mediaBudget",
        label:
          "What monthly media budget can the raise fund? Media is billed by the platform to you, separate from Ascent's flat fee.",
        options: [
          { label: "Under $15,000", qualifies: false },
          { label: "$15,000–$30,000", qualifies: true },
          { label: "$30,000–$50,000", qualifies: true },
          { label: "More than $50,000", qualifies: true },
        ],
      },
      {
        key: "trackRecord",
        label: "Have you raised before?",
        options: [
          { label: "Yes — this is not our first raise", qualifies: true },
          { label: "We operate an evergreen vehicle", qualifies: true },
          { label: "This is our first raise", qualifies: false },
        ],
      },
      {
        key: "role",
        label: "What's your role on the raise?",
        options: [
          { label: "Sponsor principal or head of investor relations", qualifies: true },
          { label: "Counsel, general counsel, or CFO", qualifies: true },
          { label: "Someone else on the team", qualifies: false },
        ],
      },
    ],
    stepLabel: "Step {n} of {total}",
    backLabel: "Back",
    continueLabel: "Continue",
    contactHeading: "Last step — how do we reach you?",
    contactSub: "If it fits, your booking link is on the next screen.",
    submitLabel: "See if it fits",
    submittingLabel: "Sending…",
    passHeading: "It fits.",
    passBody:
      "Grab a time below — thirty minutes on your last raise's numbers, in dollars, no obligation. Bring counsel if you like.",
    passFallbackBody:
      "Your request is in. You'll get a call or an email within one business day to set a time.",
    declineHeading: "A call isn't the right next step yet.",
    // Honest, not discouraging. Someone who gets this screen should be able
    // to tell exactly what would change the answer.
    declineBody:
      "Based on your answers, either the structure wouldn't clear or the arithmetic wouldn't fund a stable campaign plus the fee — usually a 506(b) offering, no securities counsel yet, or a raise under $10 million. Your answers still landed with us. If something changes — a 506(c) filing, counsel engaged, a larger vehicle — the answer changes with it.",
    // Practice claims only. No guarantee, no result, no number that isn't
    // on the page already.
    trustItems: [
      "30 minutes. No cost. No obligation.",
      "A minimum of investor appointments held in 90 days, in writing — or Ascent works at no fee until it's met.",
      "Flat monthly fee. You keep 100% of what you raise.",
    ],
  },

  // /apply runs on the brand vertical.
  applyPage: null,

  thanks: {
    h1: "Your request is in.",
    body: [
      "You'll get a call or an email within one business day to set a time for the scoping call.",
      "Before the call, round up the numbers from your last raise — media spent, leads generated, meetings held. Real numbers make it a better call.",
    ],
    backLabel: "Back to the site",
  },

  footer: {
    tagline: "Investor acquisition for 506(c) real estate sponsors",
    locationLine: "Oklahoma City, OK · Delivery is remote, nationwide",
    privacyLabel: "Privacy",
    termsLabel: "Terms",
    textUpdatesLabel: "Text updates",
    founderLabel: "About Caleb Free",
    // The brand guide's compliance footer — on every sponsor-facing page.
    complianceLine:
      "Ascent is not a broker-dealer, finder or placement agent. Compensation is a flat monthly fee — nothing tied to capital raised, investors acquired, or appointments booked. Verification of accredited status remains with the issuer. Nothing on this page is an offer to sell or a solicitation of an offer to buy any security.",
  },
};

/*
 * Sections only the dark template has. Hero stats are statements of how
 * Ascent operates — never outcomes — and the disclosure under them says so.
 */
export const sponsorsPage: SponsorPageContent = {
  nav: {
    cta: "See if you qualify",
  },

  hero: {
    kicker: "Real estate · Rule 506(c) · Investor acquisition",
    h1: "The investor acquisition firm for real estate sponsors.",
    h1Highlight: "investor acquisition",
    sub: "Ascent builds the investor pipeline for your syndication, multifamily, or CRE raise under Rule 506(c). Precision audience targeting, battle-tested funnels, counsel-approved media, and instrumented lead response feed a live setter who turns leads into meetings that are actually held. Flat monthly fee. Nothing tied to capital raised.",
    primaryCta: "See if you qualify",
    secondaryCta: { label: "How it works", href: "#process" },
    patrioticLine: "100% American owned & operated.",
    cards: [
      {
        icon: "calendar",
        label: "Week 1",
        title: "Investor calls from the first week live.",
        body: "The lane is live in fourteen days from access and approvals, and the setter is on the phone with your investor leads in the first week — not after a ramp.",
      },
      {
        icon: "stack",
        label: "Next raise",
        title: "Every lead stays on a list you own.",
        body: "Accredited-investor leads, recordings and pipeline live in a CRM registered to you, so the next raise starts from a warmer list than this one did.",
      },
      {
        icon: "shield",
        label: "Guaranteed",
        title: "A minimum of appointments held, in writing.",
        body: "Each proposal sets a minimum number of investor appointments held in the first ninety days, from your own media budget and history. Miss it, and Ascent keeps working at no fee until it's met.",
      },
      {
        icon: "target",
        label: "100%",
        title: "You keep 100% of what you raise.",
        body: "Ascent handles everything from the creative to the setter who gets the meeting onto your calendar. You show up. Ascent is a flat-fee firm — nothing tied to capital raised.",
      },
    ],
    disclosure:
      "Guarantee terms — the appointment minimum, its conditions and the remedy — are set in writing in each proposal.",
  },

  problems: {
    eyebrow: "WHY RAISES STALL",
    h2: "Why most syndications struggle to fill the investor pipeline.",
    sub: "Three failures, and the one most vendors are paid to ignore is the last one.",
    cards: [
      {
        icon: "target",
        title: "No repeatable investor pipeline",
        body: "Most sponsors raise from a personal network, a country club and warm introductions. When that runs dry the deal doesn't fill — and there is no system for sourcing the next accredited investor.",
      },
      {
        icon: "shield",
        title: "Built for one profession, not both",
        body: "Marketing agencies write manufactured urgency into what is legally a securities communication. Securities lawyers know the rules but can't run a media buy — so a raise gets one discipline or the other, never both.",
      },
      {
        icon: "calendar",
        title: "Meetings booked, not held",
        body: "A $25K–$500K decision is long and high-diligence. Without confirmation, reschedules and a nurture sequence between touches, booked meetings quietly stop happening — and the report never says so.",
      },
    ],
    // No published figure remains in this row — the 2% benchmark now lives
    // in the guides (see cost-per-investor-lead-506c-benchmarks), attributed
    // there. Don't restore this note without a number on the page for it to
    // attach to.
    note: null,
  },

  /*
   * The alternatives, compared on fee model and scope — never on outcomes,
   * and never by name. Every figure here is a standard published industry
   * range, labelled as such in the note.
   */
  comparison: {
    eyebrow: "THE ALTERNATIVES",
    h2: "Four ways to fill a raise. One of them is a flat fee.",
    sub: "What a sponsor is usually choosing between, and where the money actually goes in each.",
    rows: [
      {
        name: "A media-only agency",
        cost: "Monthly retainer",
        body: "Builds the funnel and hands you leads. The service list stops there — calling, appointment setting and investor-relations staffing are somebody's problem, and that somebody is you.",
      },
      {
        name: "A placement agent",
        cost: "6–8% of capital raised",
        body: "Registered, and priced like it. On a $10 million raise that is $600,000 to $800,000, and it comes out of your equity rather than your marketing budget.",
      },
      {
        name: "An in-house IR hire",
        cost: "$90K–$140K a year",
        body: "Fully loaded, and fixed whether you are raising this quarter or not. You still buy the media, build the compliance workflow, and do the recruiting yourself.",
      },
      {
        name: "Ascent",
        cost: "Flat monthly fee",
        body: "Counsel-approved media, instrumented response, and a live scripted setter who gets the meeting held — inside one compliance gate. Nothing is tied to capital raised, so you keep 100% of it.",
        highlight: true,
      },
    ],
    note: "Placement-agent and in-house figures are standard published industry ranges, not quotes. Ascent's fee is quoted in writing after the scoping call.",
  },

  process: {
    eyebrow: "HOW IT WORKS",
    h2: "Our real estate investor acquisition process.",
    sub: "Four stages, each with a written output. Your counsel signs before anything runs, and the conversation about your offering is the only one that stays yours.",
    steps: [
      {
        icon: "shield",
        title: "Scope, and clear compliance",
        body: "We read your last raise's numbers and interview whoever calls the leads today. In parallel, the nine-condition gate closes with your securities counsel: exemption confirmed, approver named, every legend and the full setter script approved in writing.",
      },
      {
        icon: "stack",
        title: "Build the lane",
        body: "Campaign architecture and counsel-approved creative, a CRM and pipeline you own, telephony registered in your name, instant text-and-email acknowledgement, and instrumentation that timestamps first touch and first human touch separately. Live in fourteen days from access and approvals.",
      },
      {
        icon: "phone",
        title: "Run the media and the phone",
        body: "LinkedIn for accredited-investor quality, Meta for volume, Google for existing demand. A live setter, recruited and supervised by Ascent, calls every inbound investor lead as you, confirms attendance, reschedules no-shows and logs every outcome. Every call recorded.",
      },
      {
        icon: "chart",
        title: "Report and optimize, weekly",
        body: "Fifteen minutes a week on the four numbers: speed to first human touch, contact rate by response bucket, set-to-held rate, and cost per appointment held. Long-form reviews at thirty, sixty and ninety days. Creative refreshed on fatigue; budget moved on evidence.",
      },
    ],
    cta: "Book a scoping call",
  },

  included: {
    eyebrow: "FULL-SERVICE INVESTOR ACQUISITION",
    h2: "What's included in the Ascent system.",
    sub: "End-to-end investor acquisition for real estate sponsors — everything from the first impression to the meeting that is held, inside a structure your counsel approved.",
    cards: [
      {
        icon: "megaphone",
        title: "Accredited-investor media lane",
        bullets: [
          "LinkedIn, Meta and Google campaigns built for real estate investor acquisition",
          "Every ad drafted against the metrics your counsel approved — no projected returns, no manufactured urgency",
          "Media billed by the platform to your own account; never held, advanced or marked up",
        ],
      },
      {
        icon: "stack",
        title: "Investor-grade assets",
        bullets: [
          "Landing pages and lead forms carrying the legends your counsel specifies, verbatim",
          "Staged nurture sequences by text and email, from your name",
          "A CRM and pipeline you own, with source and creative recorded on every lead",
        ],
      },
      {
        icon: "loop",
        title: "Instrumented lead response",
        bullets: [
          "Instant acknowledgement of every lead, within seconds",
          "First touch and first human touch timestamped as separate fields",
          "Contact rate and set rate bucketed by response time",
        ],
      },
      {
        icon: "phone",
        title: "A live, scripted setter",
        bullets: [
          "Recruited, trained and supervised by Ascent; calls as you, from a number registered to you",
          "Logistics only — never the offering. A breach is a stop-work event",
          "Attendance confirmed before every meeting; every call recorded for you and counsel",
        ],
      },
      {
        icon: "shield",
        title: "Compliance gate and governance",
        bullets: [
          "Nine written conditions close before anything publishes or anyone dials",
          "One complete package to counsel, one review deadline of three business days",
          "A lapsed approval stops calling the same day, in writing",
        ],
      },
    ],
    ctaCard: {
      title: "Ready to see what one appointment held costs?",
      body: "Six questions. If it fits, the calendar is on the next screen.",
      cta: "See if you qualify",
    },
  },

  ctaBand: {
    h2: "Ready to find out where your last raise's leads went?",
    body: "Thirty minutes on your numbers, in dollars. Counsel welcome. If it doesn't fit, we'll say so on the call.",
    cta: "Book a scoping call",
  },

  /*
   * The entity block. The definition is the one sentence to be quoted
   * whole; every fact is a practice, a term or a boundary — nothing here
   * is a result.
   */
  glance: {
    eyebrow: "ASCENT AT A GLANCE",
    h2: "What Ascent is, in one paragraph.",
    definition:
      "Ascent is a flat-fee investor acquisition firm for U.S. real estate syndicators and private real estate fund sponsors raising under Rule 506(c). It runs counsel-approved paid media on LinkedIn, Meta and Google, instrumented lead response, and a live, scripted appointment setter who calls every inbound investor lead as the sponsor — and reports one primary number, cost per appointment held. Ascent is not a broker-dealer, finder or placement agent, never verifies accredited status, and takes nothing tied to capital raised.",
    facts: [
      { label: "Serves", value: "U.S. real estate sponsors — multifamily, industrial, self-storage, build-to-rent, opportunity zone, real estate credit" },
      { label: "Offerings", value: "Rule 506(c) and Regulation A+ only. Never 506(b)" },
      { label: "Minimums", value: "$10M+ live raise or an evergreen vehicle; $15K+ monthly media; securities counsel engaged" },
      { label: "Fee model", value: "Flat monthly fee, scaling with media under management. Nothing tied to capital raised" },
      { label: "In writing", value: "A minimum of investor appointments held in 90 days, or Ascent works at no fee until it's met" },
      { label: "Calls", value: "Live, human, scripted, recorded. Inbound leads only. Logistics only — never the offering" },
      { label: "Live in", value: "14 days from account access and counsel's approvals" },
      { label: "Reports", value: "Weekly: speed to first human touch, contact rate, set-to-held rate, cost per appointment held" },
      { label: "Based in", value: "Oklahoma City, Oklahoma. Delivery is remote, nationwide. 100% American owned and operated" },
      { label: "Founder", value: "Caleb Free — see ascentcas.com/caleb-free" },
    ],
  },

  guides: {
    eyebrow: "GUIDES",
    h2: "The rules and the arithmetic, written down.",
    sub: "What sponsors and their counsel ask before a scoping call — the exemptions, verification, the published economics of investor leads, and the fee models. No pitch; the sources are at the bottom of each one.",
    indexLabel: "All guides",
  },

  legal: {
    heading: "Legal disclosures",
    paragraphs: [
      "Ascent Client Acquisition Systems LLC provides marketing, lead-response, appointment-setting and reporting services only. Ascent is not a registered broker-dealer, placement agent, finder, investment adviser or funding portal, and does not act in any fiduciary capacity.",
      "Ascent does not offer, sell or distribute securities; does not solicit the purchase or sale of any security; does not make investment recommendations or give investment advice; does not structure, price or negotiate offering terms; does not verify accredited-investor status; and does not handle investor funds or subscription documents. Setters place logistical calls only, under the sponsor's name and on a script approved by the sponsor's securities counsel, and every call is recorded.",
      "Compensation is a flat monthly fee. Ascent does not receive and will not accept any commission, success fee, finder's fee or other transaction-based compensation, including any compensation tied to capital raised, investors introduced or acquired, or appointments booked or held.",
      "Nothing on this site is an offer to sell or a solicitation of an offer to buy any security, nor investment, legal or tax advice. Any offering is made only by the issuer under its own offering documents, under the direction of its counsel, and only to eligible investors in permitted jurisdictions. Benchmark figures on this page are published third-party category figures, are not Ascent results, and do not guarantee any outcome.",
    ],
  },
};

export default sponsors;
