import type { SponsorPageContent, Vertical } from "./types";

/*
 * ascentforsponsors.com — investor acquisition for real estate syndicators
 * and private real estate fund sponsors raising under Reg D Rule 506(c).
 *
 * Served at /sponsors and, via the host rewrite in next.config.ts, as the
 * ROOT of ascentforsponsors.com. Rendered by the dark sponsor template
 * (src/components/sponsor/SponsorPage.tsx), which reads this `Vertical`
 * for the gate, booking, benchmarks, boundaries, fit, FAQ and footer, and
 * the `sponsorsPage` export below for the sections only that template has.
 * `business.url` and `canonicalUrl` point at that domain, so the canonical,
 * JSON-LD, robots and sitemap all describe the sponsor site whichever host
 * actually served the request.
 *
 * Sources: the Ascent business plan (RE sponsors, second edition, Sept
 * 2026), the Brand Style Guide v2.0, Delivery Boundaries v2.0, and the
 * metrics ontology. Several conventions here are compliance positions, not
 * style choices — keep them when editing:
 *
 *   - "appointment held", never set / booked / scheduled.
 *   - "investor lead", never prospect or qualified investor.
 *   - "flat monthly fee" — nothing tied to capital raised, investors
 *     acquired, or appointments held. The one guarantee on this page is the
 *     proposal's own: a minimum of appointments HELD in 90 days or the fee
 *     stops until it's met — never a result, never anything about capital.
 *     (The brand guide's default is no guarantee in collateral; the owner
 *     chose to publish this one, in the proposal's exact terms.)
 *   - "sponsor" / "issuer"; the investors are never Ascent's.
 *   - Live, human, scripted calls only. The automated channels are texts
 *     and emails — write the channel out; never "automated calls".
 *   - No pricing published. It is quoted in writing after the scoping call
 *     (`pricing: null`, `expectations` in its place).
 *   - Every number on the page traces to the metrics ontology or to a
 *     published, attributed category benchmark. No Ascent results are
 *     published until a sponsor agrees to a named, written case study.
 */
/*
 * The sponsor page's content date — the sitemap lastmod and the WebPage
 * dateModified. Bump it when the page's copy changes; a build date would
 * tell crawlers the page changed on every deploy, which it does not.
 */
export const SPONSOR_PAGE_UPDATED = "2026-10-09";

const sponsors: Vertical = {
  slug: "sponsors",
  path: "/sponsors",
  canonicalUrl: "https://ascentforsponsors.com",

  business: {
    name: "Ascent",
    url: "https://ascentforsponsors.com",
    city: "Oklahoma City",
    region: "OK",
    // Delivery is entirely remote; the firm sells nationally.
    areaServed: "United States",
    // The registered street address. Rendered in the footer and in the
    // contact sections of /privacy and /terms, and in the JSON-LD address.
    street: "204 N Robinson Ave",
    postalCode: "73102",
    phone: "405-563-7863",
    // The sponsor domain's own mailbox — footer, /privacy and JSON-LD pick
    // it up. It must exist and be monitored; nothing on the site sends to it.
    email: "info@ascentforsponsors.com",
    // Entity facts for the Organization JSON-LD and the guide bylines.
    legalName: "Ascent Client Acquisition Systems LLC",
    founder: { name: "Caleb Free", title: "Founder" },
    // The firm's own profile URLs (LinkedIn company page, etc.). Empty until
    // the owner supplies them — never guess a URL here.
    sameAs: [],
  },

  // The call this vertical books, as the transactional SMS consent
  // sentence names it (content/compliance.ts).
  smsCallName: "scoping call",

  seo: {
    // A vertical owns its whole title (src/lib/metadata.ts sets it
    // absolute), so the brand suffix is written out here. Leads with the
    // two names the buyer actually searches — syndicator and 506(c)
    // sponsor.
    title: "Investor Acquisition for Real Estate Syndicators & 506(c) Sponsors | Ascent",
    description:
      "We find accredited investors for real estate sponsors raising under Rule 506(c). Ads your lawyer approves, fast follow-up, and a live setter who turns leads into meetings that really happen. One flat monthly fee.",
    // The v3 lockup on ink, generated by scripts/build-v3-assets.mjs.
    ogImage: "/og-sponsors.png",
  },

  header: {
    cta: "Book a call",
  },

  hero: {
    // The one eyebrow the brand guide mandates. "(c)" survives the CSS
    // uppercase via EyebrowText — it is a rule citation, not a letter.
    eyebrow: "INVESTOR ACQUISITION FOR 506(c) SPONSORS",
    h1: "Investor meetings held, not just investor leads.",
    // The orange lands on the promise, never on the problem.
    h1Highlight: "Investor meetings held",
    sub: "Roughly two percent of investor leads become investors. Most of the rest were never called, or were called days later by someone reading no script — and you paid to generate every one. Ascent works the other ninety-eight: a live setter calling as you, inside a structure your securities counsel approved in writing.",
    closingLine: "You run the investor conversation. We run everything before it.",
    cta: "See if you qualify",
    secondaryCta: null,
    // Practice claims only — things a sponsor or their counsel can check.
    chips: [
      "Every setter call recorded",
      "Counsel-approved script",
      "Cost per appointment held",
    ],
    // Illustrative week — generic labels only, never names, funds, dollar
    // figures, or counts presented as results.
    calendar: {
      title: "Your calendar — this week",
      days: ["Mon", "Tue", "Wed", "Thu"],
      times: ["9:00", "11:00", "1:00", "3:00"],
      blocks: [
        { day: 0, row: 1, label: "Investor meeting", time: "11:00", kind: "booked" },
        { day: 1, row: 0, label: "Setter call", time: "9:30 · REC", kind: "call" },
        { day: 1, row: 2, label: "Investor meeting", time: "1:00", kind: "booked" },
        { day: 2, row: 1, label: "Investor meeting", time: "11:30", kind: "booked" },
        { day: 2, row: 3, label: "Setter call", time: "3:15 · REC", kind: "call" },
        { day: 3, row: 0, label: "Investor meeting", time: "9:00", kind: "booked" },
        { day: 3, row: 2, label: "Investor meeting", time: "1:30", kind: "booked" },
      ],
      caption:
        "Investor leads called back by a live setter, as you, on a script your counsel approved — then confirmed onto your calendar.",
    },
    microcopy: "30 minutes. Free. No strings. Bring your lawyer if you like.",
  },

  /*
   * Cost per appointment held — the primary metric — from the sponsor's own
   * assumptions. Deliberately NOT a revenue or capital-raised projection:
   * that would be a performance claim this page must not make.
   */
  calculator: {
    kind: "appointments",
    fields: {
      mediaBudget: {
        label: "Monthly media budget",
        min: 5000,
        max: 100000,
        step: 1000,
        defaultValue: 15000,
        unit: "$",
        numberInput: true,
      },
      costPerLead: {
        label: "Cost per investor lead",
        min: 25,
        max: 500,
        step: 5,
        defaultValue: 75,
        unit: "$",
        numberInput: true,
      },
      contactRate: {
        label: "Leads that get a connected touch",
        min: 10,
        max: 90,
        step: 1,
        defaultValue: 40,
        unit: "%",
        numberInput: false,
      },
      heldRate: {
        label: "Contacted leads whose meeting is held",
        min: 5,
        max: 60,
        step: 1,
        defaultValue: 20,
        unit: "%",
        numberInput: false,
      },
    },
    outputs: {
      leads: "Investor leads / month",
      costPerHeld: "Cost per appointment held",
      held: "Appointments held / month",
      uncontacted: "Leads never contacted / month",
    },
    assumptionLine:
      "Arithmetic on your assumptions, not a projection: budget ÷ cost per lead, × the share reached, × the share whose meeting is held. Cost per lead defaults to the published Meta benchmark for this category; the two rates are yours to set. Media spend only — the fee never enters a cost-per number unless a report says fully loaded.",
  },

  calculatorSection: {
    eyebrow: "RUN YOUR RAISE'S NUMBERS",
    h2: "What does one investor appointment held cost you?",
    sub: "Set your media budget and cost per lead, then the two rates nobody tracks — how many leads get a connected touch, and how many of those turn into a meeting that is actually held. That last number is the one we manage to.",
  },

  problem: {
    eyebrow: "THE ACTUAL PROBLEM",
    h2: "Your raise isn't short on leads. It's short on the first ninety seconds after one arrives.",
    paragraphs: [
      "An accredited investor fills out the form on your ad. They get an email autoresponder. A human calls them three days later, if at all, working from no script, on a line nobody records. Your agency reports the lead as delivered — and by its definition, it was.",
      "Every agency in this category sells the top of that funnel: targeting, landing pages, creative, nurture. Their published service lists contain no live calling, no appointment setting, and no investor-relations staffing. The published lead-to-investor rate is about two percent, and nobody in the chain is paid to move it.",
      "Capital-raise marketing sits in the gap between two professions. Marketing agencies write manufactured urgency into what is legally a securities communication. Securities lawyers know the rules and cannot run a media buy. Neither one measures speed to lead, contact rate, or whether a meeting that was booked was ever held.",
      "Ascent is built to sit in that gap on purpose. It runs the media, staffs the phone with a live setter calling as you, instruments every touch, and does all of it inside a structure your securities counsel has approved in writing before anything publishes.",
    ],
  },

  /*
   * The diagram. Stage copy describes what the system DOES — never counts,
   * rates, or dollars. Badges are statements of how the firm operates.
   */
  // Rendered as the numbered process in `sponsorsPage` instead.
  systemFlow: null,

  // Rendered as the feature grid in `sponsorsPage` instead.
  services: null,

  // Folded into services.ownerCard on this page.
  howItWorks: null,

  /*
   * Required by the Vertical interface and used by the light template's
   * ProofSection — the dark sponsor template does not render it. The 2%
   * figure it carries is attributed in `sponsorsPage.problems.note`, where
   * that number now appears on the page.
   */
  proof: {
    srHeading: "The category's published numbers",
    framingLine:
      "The category publishes its own failure rate. These are the published benchmarks for 506(c) investor acquisition — not Ascent's numbers, and the reason the setter exists.",
    stats: [
      { number: "~2%", label: "of investor leads become investors" },
      {
        number: "$50–$100",
        label: "cost per investor lead on Meta; LinkedIn runs roughly five times that",
      },
      {
        number: "$3.5K–4.5K",
        label: "cost per funded investor, within 90 days of first contact",
      },
    ],
    // A published source, not a client result. Ascent publishes none of its
    // own sponsor numbers until a sponsor agrees to a named, written case
    // study — never fill this with an unattributed figure.
    attributionLine:
      "Published category benchmarks for real estate 506(c) investor marketing (GowerCrowd). Ascent reports its own numbers to each sponsor weekly and publishes none of them without a named, written case study.",
    reportCard: null,
    screenshots: [],
  },

  /*
   * Practice claims only — what a sponsor or their counsel can check.
   * Numbers live in `proof`, attributed.
   */
  // Folded into the process and feature grid in `sponsorsPage`.
  transparency: null,

  // No longer rendered on the page (removed at the owner's request,
  // 2026-10-07); kept for /sponsors/llms.txt, where answer engines read it.
  boundaries: {
    eyebrow: "WHAT WE NEVER DO",
    h2: "The terms on which Ascent is not a broker.",
    intro:
      "On a capital-raise engagement these are not scope decisions. They are absolute, they are in the contract, and they are the reason your securities counsel can approve the structure without redrafting it.",
    items: [
      {
        title: "Flat monthly fee. Nothing else.",
        body: "Nothing tied to capital raised, investors acquired, or appointments held. Never traded for upside, at any performance level. The CRM has no field for it, so it cannot be argued about.",
      },
      {
        title: "The setter never discusses the offering.",
        body: "No returns, valuation, merits, timing, or terms. Every touch is logistical. A breach is a stop-work event, not a coaching moment.",
      },
      {
        title: "Verification stays with you, permanently.",
        body: "Ascent never asks about, assesses, or verifies accredited-investor status. Ascent never touches funds and never gives investment advice.",
      },
      {
        title: "Nothing publishes and nobody dials without counsel approval.",
        body: "If an approval lapses, calling stops the same day, in writing. If your counsel raises a question, the lane pauses until it is answered.",
      },
      {
        title: "Live, human, scripted calls only.",
        body: "No prerecorded audio, no artificial voice, no robo-dialing. Only inbound leads you generated — never a purchased list, never a scraped number, never your old database without scoping it first.",
      },
      {
        title: "Everything built belongs to you.",
        body: "The phone number is registered to you. The recordings are yours. The investor list is yours at the end, whether or not you stay.",
      },
    ],
    closing:
      "Your counsel receives one complete package — the script, the legends, the approval workflow, and the express no-transaction-based-compensation clause — with one review deadline. The point is to remove work from their desk, not to argue with it.",
  },

  fit: {
    eyebrow: "WHO THIS IS FOR",
    h2: "Built for a small group of sponsors. On purpose.",
    forYouHeading: "This is for you if",
    forYou: [
      "You are a U.S. real estate sponsor. That could be multifamily, industrial, self storage, build to rent, opportunity zones or real estate credit.",
      "You have a live Rule 506(c) offering of $10 million or more. Or you run an evergreen fund that is always raising.",
      "You already have a securities lawyer. One named person there can review our work in three business days.",
      "You can spend at least $15,000 a month on ads. You pay the ad platform directly, on your own account.",
      "You have raised before, and your network has stopped filling the deal.",
    ],
    notForYouHeading: "This is not for you if",
    notForYou: [
      "The offering is 506(b). That rule bans general solicitation (public ads), and no vendor can change that.",
      "You have no securities lawyer. Our legal checks can't clear without one.",
      "It is one property under $10 million with no fund behind it. The math won't pay for steady ads plus our fee.",
      "You are in the middle of a capital call, or you have paused payouts to investors.",
      "You want us paid based on money raised. That is the one term we will never sign.",
    ],
    note: "Close, but not quite? Book the call anyway and tell us. The answer might be \"not yet,\" and that still helps.",
  },

  // No published pricing on this page — quoted in writing after the call.
  pricing: null,

  // Folded into the process steps in `sponsorsPage`.
  expectations: null,

  // No performance guarantee ever attaches to a regulated raise.
  guarantees: null,

  /*
   * Every answer restates facts already published on this page — the
   * boundaries, the owner-card steps, the expectations. Nothing new is
   * claimed here; if a fact changes above, change it here too.
   */
  // Brought up to date 2026-10-07 from the Company Hub: Offers & Pricing
  // (packages, implementation, billing, term, Diagnostic), Delivery
  // Boundaries (the calling rule, reactivation, securities terms) and
  // ICP & Messaging Pillars. Still no prices on the page.
  // Cut to the five most-asked questions on 2026-10-09 (owner's request).
  faq: {
    eyebrow: "FREQUENTLY ASKED QUESTIONS",
    h2: "What sponsors and their lawyers ask first.",
    items: [
      {
        q: "What does it cost?",
        a: "There are two plans. Both cost one flat fee each month. In Managed Investor Pipeline, Ascent hires, trains and manages a live setter for your leads. In Investor Pipeline, your own staff answers the leads, and we give them the system and training. Each plan has a one-time setup fee. You pay for ads separately, straight to the platform. We quote the numbers in writing after the call, once we've seen yours.",
      },
      {
        q: "How is it billed, and how long is the commitment?",
        a: "You pay for setup in two halves. The first is due at kickoff. The second is due only when the system passes the tests we agreed on. The monthly fee starts when your ads launch, once a written checklist is done. You start with 90 days. After that it's month to month, with 30 days' notice to stop.",
      },
      {
        q: "What results can we expect?",
        a: "We don't share client numbers unless a client agrees to a named, written case study. Nothing on this site predicts how much money you'll raise. What you get in writing is a minimum number of investor meetings held in the first 90 days. We set it in your proposal from your ad budget and past results. If we miss it, we keep working for free until we hit it. You also get a weekly dashboard on cost per meeting held. It shows ad cost apart from total cost.",
      },
      {
        q: "Is Ascent a broker-dealer, finder or placement agent?",
        a: "No. We charge one flat monthly fee. Nothing is tied to money raised, investors gained or meetings booked, no matter the results. Ascent never touches funds, never checks who is accredited and never gives investment advice. These terms are in the contract, not just a policy.",
      },
      {
        q: "Who makes the calls, and what do they say?",
        a: "American setters based in the U.S. Ascent hires, trains and manages them. They only call new leads that came from your own ads. They call in your name, from a number registered to you, using a written script your lawyer approved. They only handle the basics: checking that the lead asked to hear from you, and putting a meeting on your calendar. They never talk about returns, value, merits, timing or terms. Every call is recorded.",
      },
    ],
  },

  booking: {
    eyebrow: "BOOK A CALL",
    h2: "Find out where your last raise's leads went.",
    body: "Thirty minutes. Bring the numbers from your last raise: what you spent on ads, how many leads you got and how many meetings really happened. We'll show you, in dollars, what the gap between leads and meetings is costing you. We'll also tell you if this setup will pass your lawyer's review. If it's not a fit, we'll say so on the call.",
    // The GoHighLevel (LeadConnector) booking widget, supplied 2026-09-27,
    // replacing the Calendly scoping-call event. Scheduling now sits in the
    // same system the leads already land in, so a booked appointment is on
    // the contact record rather than in a second tool.
    //
    // The trailing path segment is the calendar's id. src/lib/scheduler.ts
    // reads the provider off the /widget/booking/ path, then derives the
    // resize script and the message origin from this same URL, so moving
    // to another white-label host or another calendar is a change here and
    // nowhere else.
    schedulingLink:
      "https://links.ascentforsponsors.com/widget/booking/2qqDWLxVgjzCoxlnlRPb",
    // Legacy form labels — the gate below is the live path.
    form: {
      nameLabel: "Name",
      companyLabel: "Sponsor or fund",
      phoneLabel: "Phone",
      emailLabel: "Email",
      estimatesSelectLabel: "Offering status",
      estimatesSelectOptions: [
        "Open 506(c) raise, advertising now",
        "Open 506(c) raise, not yet advertising",
        "Filing in the next 90 days",
        "506(b), or not sure",
      ],
      tradeField: null,
      submitLabel: "Request a call",
      submittingLabel: "Sending…",
    },
  },

  // The ICP gate in front of the scheduler. A prospect qualifies only when
  // EVERY chosen option carries `qualifies: true`. The thresholds are the
  // ideal-client definition from the business plan: a live 506(c) (or
  // Reg A+) offering of $10M+ or an evergreen vehicle, counsel engaged, a
  // media budget of $15K/month or more, a track record, and a buyer who
  // can actually say yes — the sponsor principal, head of IR, or the
  // compliance owner.
  qualification: {
    nameLabel: "Name",
    companyLabel: "Sponsor or fund",
    phoneLabel: "Phone",
    emailLabel: "Email",
    questions: [
      {
        key: "exemption",
        label: "Which SEC rule is your offering under?",
        options: [
          { label: "Rule 506(c) (we can advertise)", qualifies: true },
          { label: "Regulation A+", qualifies: true },
          { label: "Rule 506(b)", qualifies: false },
          { label: "Not sure yet", qualifies: false },
        ],
      },
      {
        key: "raiseSize",
        label: "How big is the offering?",
        options: [
          { label: "Under $10 million", qualifies: false },
          { label: "$10 to $25 million", qualifies: true },
          { label: "$25 to $50 million", qualifies: true },
          { label: "More than $50 million", qualifies: true },
          { label: "Evergreen (always raising)", qualifies: true },
        ],
      },
      {
        key: "counsel",
        label: "Do you have a securities lawyer on this offering?",
        options: [
          { label: "Yes", qualifies: true },
          { label: "Not yet", qualifies: false },
        ],
      },
      {
        key: "mediaBudget",
        label:
          "How much can the raise spend on ads each month? The ad platform bills you for this. It is separate from Ascent's flat fee.",
        options: [
          { label: "Under $15,000", qualifies: false },
          { label: "$15,000 to $30,000", qualifies: true },
          { label: "$30,000 to $50,000", qualifies: true },
          { label: "More than $50,000", qualifies: true },
        ],
      },
      {
        key: "trackRecord",
        label: "Have you raised before?",
        options: [
          { label: "Yes, this is not our first raise", qualifies: true },
          { label: "We run an evergreen fund", qualifies: true },
          { label: "This is our first raise", qualifies: false },
        ],
      },
      {
        key: "role",
        label: "What's your role on the raise?",
        options: [
          { label: "Sponsor owner or head of investor relations", qualifies: true },
          { label: "Lawyer, general counsel or CFO", qualifies: true },
          { label: "Someone else on the team", qualifies: false },
        ],
      },
    ],
    stepLabel: "Step {n} of {total}",
    backLabel: "Back",
    continueLabel: "Continue",
    contactHeading: "Last step: how do we reach you?",
    contactSub: "If it fits, your booking link is on the next screen.",
    submitLabel: "See if it fits",
    submittingLabel: "Sending…",
    passHeading: "It fits.",
    passBody:
      "Pick a time below. We'll spend thirty minutes on your last raise's numbers, in dollars. No strings. Bring your lawyer if you like.",
    passFallbackBody:
      "Your request is in. You'll get a call or an email within one business day to set a time.",
    declineHeading: "A call isn't the right next step yet.",
    // Honest, not discouraging. Someone who gets this screen should be able
    // to tell exactly what would change the answer.
    declineBody:
      "From your answers, either the legal setup wouldn't pass or the math wouldn't pay for steady ads plus our fee. Most often that means a 506(b) offering, no securities lawyer yet, or a raise under $10 million. We still got your answers. If something changes, like a 506(c) filing, a lawyer on board or a bigger fund, the answer changes too.",
    // Practice claims only. No guarantee, no result, no number that isn't
    // on the page already.
    trustItems: [
      "30 minutes. Free. No strings.",
      "A minimum number of investor meetings held in 90 days, in writing. If we miss it, we work for free until we hit it.",
      "One flat monthly fee. You keep 100% of what you raise.",
    ],
  },

  // /apply runs on the brand vertical.
  applyPage: null,

  thanks: {
    h1: "Your request is in.",
    body: [
      "You'll get a call or an email within one business day to set a time for the scoping call.",
      "Before the call, gather the numbers from your last raise: ad spend, leads and meetings held. Real numbers make it a better call.",
    ],
    backLabel: "Back to the site",
  },

  footer: {
    tagline: "We find investors for 506(c) real estate sponsors",
    locationLine: "Oklahoma City, OK · We work with sponsors across the U.S.",
    privacyLabel: "Privacy",
    termsLabel: "Terms",
    textUpdatesLabel: "Text updates",
    founderLabel: "About Caleb Free",
    // The brand guide's compliance footer — on every sponsor-facing page.
    complianceLine:
      "Ascent is not a broker-dealer, finder or placement agent. Compensation is a flat monthly fee — nothing tied to capital raised, investors acquired, or appointments booked. Verification of accredited status remains with the issuer. Nothing on this page is an offer to sell or a solicitation of an offer to buy any security.",
  },
};

/*
 * Sections only the dark template has. Hero stats are statements of how
 * Ascent operates — never outcomes — and the disclosure under them says so.
 */
export const sponsorsPage: SponsorPageContent = {
  nav: {
    cta: "See if you qualify",
  },

  hero: {
    // Removed at the owner's request (2026-10-05): the h1 now opens the
    // hero on its own, over the footage.
    kicker: null,
    h1: "We find investors for real estate sponsors.",
    h1Highlight: "find investors",
    sub: "We find accredited investors for your 506(c) raise and put them on your calendar. Ads your lawyer approves bring in the leads. A live American setter calls each one and sets up a real meeting. You pay one flat fee each month. We never take a cut of what you raise.",
    primaryCta: "See if you qualify",
    secondaryCta: { label: "How it works", href: "#process" },
    patrioticLine: "100% American owned and run.",
    cards: [
      {
        icon: "calendar",
        label: "Week 1",
        title: "Calling investors in week one.",
        body: "You go live 14 days after we get access and approvals. In week one, a live American setter starts calling your new investor leads. There is no slow start.",
      },
      {
        icon: "stack",
        label: "Next raise",
        title: "Your next raise starts with a list you own.",
        body: "Every lead, call recording and next step lives in a CRM in your name. A broker-dealer charges you again on your next fund. Your list does not.",
      },
      {
        icon: "shield",
        label: "Guaranteed",
        title: "Meetings held, guaranteed in writing.",
        body: "Your proposal sets a minimum number of investor meetings held in the first 90 days. We base it on your ad budget and past results. If we fall short, we keep working for free until we hit it.",
      },
      {
        icon: "target",
        label: "100%",
        title: "You keep 100% of what you raise.",
        body: "We take no load, no promote and no percentage. We run it all, from the first ad to the meeting on your calendar, for one flat monthly fee. You show up and make your case.",
      },
    ],
    disclosure:
      "Each proposal spells out the guarantee in writing: the minimum, the conditions and what we do if we miss it.",
    /*
     * The owner's "Website Banner.mov" (Drive, 2026-10-05): a 74-second 4K
     * drone reel of multifamily, office and downtown real estate. Built by
     * scripts/build-hero-video.mjs into AV1 / HEVC / H.264 at 1080p for
     * screens 640px and up, and a portrait crop for phones — near-source
     * quality (VMAF ~94) at the same ~1.3 Mbps and ~0.7 Mbps the previous
     * H.264-only files used. The poster is the opening golden-hour frame.
     */
    video: { basePath: "/video/hero" },
  },

  /*
   * Rewritten 2026-10-07 from the Company Hub's "ICP & Messaging Pillars":
   * why change (Network Ceiling, the approved core line, as the h2), why
   * this path (cost to raise), why now (rate shock). Guardrails from that
   * page: say "cost to raise", never "cost of capital"; never call a
   * co-GP arrangement illegal, only "a question for your securities
   * counsel"; frame rates as what already changed, never a forecast.
   */
  problems: {
    eyebrow: null,
    h2: "Every sponsor runs out of network before they run out of raise.",
    sub: null,
    cards: [
      {
        icon: "target",
        title: "The same list, asked twice",
        body: "Most raises start with past investors and referrals. That is how it should be. But by the time a raise is half sold, you have asked the same people twice. And you have no way to reach the accredited investors who don't know you yet.",
      },
      {
        icon: "stack",
        title: "Every other path takes a cut",
        body: "A broker-dealer network takes a percentage of every dollar it sells. Then it takes it again on your next fund. A co-GP raiser takes a slice of your promote. And pay tied to dollars raised is a question for your securities lawyer.",
      },
      {
        icon: "chart",
        title: "The raise got bigger. The network didn't.",
        body: "Rates went up, so lenders want more investor cash in every deal. Investors can also earn a safe return on Treasury bonds, so they hold you to that. You have more to raise and a higher bar to clear, with the same network you started with.",
      },
    ],
    // No published figure in this row. Add a note only with a number on
    // the page for it to attach to.
    note: null,
  },

  /*
   * The alternatives, compared on fee model and scope — never on outcomes,
   * and never by name. Every figure here is a standard published industry
   * range, labelled as such in the note.
   */
  /*
   * From the Company Hub's ICP & Messaging Pillars (Pillar A, cost to
   * raise) and its chart. Guardrails carried from that page: "cost to
   * raise", never "cost of capital"; the broker-dealer figure is "a typical
   * load", never the sponsor's actual cost; never call a broker-dealer a
   * placement agent; no Westwin figures on the public site.
   */
  // Not rendered since 2026-10-09 (owner's request). Kept with
  // src/components/sponsor/CostToRaiseChart.tsx so it can come back.
  costChart: {
    eyebrow: "WHAT THE REST OF YOUR RAISE COSTS",
    h2: "A broker-dealer charges on every dollar. Every raise.",
    sub: "With Ascent, you pay to meet each investor once. Every name stays on a list you own for your next fund. Enter your average check and how many investors you meet go on to invest. Then see what the rest of your raise costs each way.",
    // The institutional placement-agent band was dropped 2026-10-07 at the
    // owner's request: the comparison that matters to this buyer is the
    // retail broker-dealer channel, which reaches the same investors.
    load: {
      label: "Retail broker-dealer load",
      low: 0.085,
      high: 0.1,
      caveat: "Sells to individual accredited investors. It charges on every dollar, and again on your next fund.",
    },
    note: "This is simple math on your numbers. It is not a quote or a promise of results. Cost to raise = cost per meeting held ÷ commit rate ÷ average check. The broker-dealer range is the selling fee plus the dealer-manager fee shown in public offering papers filed with the SEC. FINRA caps the two at 10%. A typical load is not your actual cost.",
    cta: "Run it on your raise",
  },

  // Ascent against a typical marketing agency (owner's request,
  // 2026-10-10). Structure only, never outcomes, never a named firm. Each
  // agency cell restates a claim the page has made before: agencies sell
  // the top of the funnel and hand over leads, report leads delivered, and
  // often keep the CRM and number (ICP & Messaging Pillars, "control fear").
  comparison: {
    eyebrow: "ASCENT VS. OTHER AGENCIES",
    h2: "Other agencies stop at the lead. We go all the way to the meeting.",
    sub: "Here is how we compare to a typical marketing agency, side by side.",
    columns: [
      { name: "Ascent", highlight: true },
      { name: "A typical agency" },
    ],
    rows: [
      {
        label: "How you pay",
        cells: ["One flat monthly fee", "A monthly retainer"],
      },
      {
        label: "What you get",
        cells: ["Meetings held with investors", "Leads"],
      },
      {
        label: "Who calls new leads",
        cells: [
          "A live American setter, in your name, on your script",
          "No one. They hand the leads to you",
        ],
      },
      {
        label: "Legal review",
        cells: [
          "Your lawyer approves every ad and script before anything runs",
          "Often written like a sales promo, not a securities message",
        ],
      },
      {
        label: "What they report",
        cells: ["Cost per meeting held, every week", "Leads delivered"],
      },
      {
        label: "Who keeps the CRM, number and data",
        cells: ["You. It is all in your name", "Often the agency"],
      },
    ],
    note: "This compares how a typical agency is set up, not any one firm. We quote our fee in writing after the call.",
  },



  process: {
    eyebrow: "HOW IT WORKS",
    h2: "How we find your investors, step by step.",
    sub: "Four steps. Each one ends with something in writing. Your lawyer signs off before anything runs. The talk about your offering always stays with you.",
    // Rewritten 2026-10-07 from the Company Hub's Offers & Pricing
    // (implementation deliverables, milestone billing, delivery limits,
    // term) and Delivery Boundaries (the calling rule).
    steps: [
      {
        icon: "shield",
        title: "Plan it, and clear it with your lawyer",
        body: "First, we talk about your raise, your leads today and who answers them. Then you get a written plan and a check of your current funnel. Your securities lawyer approves the setter setup, the script and every ad before anything goes live or anyone calls.",
      },
      {
        icon: "stack",
        title: "Build the system",
        body: "We build two landing pages with a form and a calendar. We set up a CRM in your name and track where each lead comes from. We write text and email follow-ups, the setter script and ten starter ads from your materials. You pay the second half of setup only after the system passes the tests we agreed on.",
      },
      {
        icon: "phone",
        title: "Launch, and answer every lead",
        body: "Your ads go live on one main platform, billed to your own ad account. A live setter calls every new lead in your name, from your number, using the approved script. Ascent hires, trains and manages the setter. The setter puts the meeting on your calendar. You run the meeting.",
      },
      {
        icon: "chart",
        title: "Report each week on meetings held",
        body: "Each week you get a dashboard and a review built on cost per meeting held. We show ad cost apart from total cost. You get six new ads a month, and a landing page test when there is enough traffic. You start with 90 days, then go month to month.",
      },
    ],
    cta: "Book a call",
  },

  // Rewritten 2026-10-07 from the Company Hub's Offers & Pricing (the
  // Managed Investor Pipeline scope, implementation deliverables and
  // ongoing delivery limits) and Delivery Boundaries. No prices: the fee
  // is quoted in writing after the scoping call.
  included: {
    eyebrow: "EVERYTHING INCLUDED",
    h2: "What you get with Ascent.",
    sub: "Ads, follow-up and a live setter, run as one system. It goes from the first ad to the meeting that happens, all inside a setup your lawyer approved. Everything we build is yours.",
    cards: [
      {
        icon: "megaphone",
        title: "Ads that reach accredited investors",
        bullets: [
          "Ads on Meta, Google and X, built to find real estate investors. We start on one main platform",
          "Ten starter ads from your materials, then six new ones every month",
          "Every ad written around the numbers your lawyer approved",
          "You pay the platform for ads on your own account. We never hold, front or mark up that money",
        ],
      },
      {
        icon: "stack",
        title: "Pages, CRM and follow-up",
        bullets: [
          "Two landing pages with a form and a calendar. Your lawyer's legal wording appears word for word",
          "Approved texts and emails that reply, remind and reschedule, all from your name",
          "A CRM in your name that records where every lead came from",
          "Your data, numbers and assets stay yours. If you leave, we hand them over with a written record",
        ],
      },
      {
        icon: "loop",
        title: "Fast replies and weekly reports",
        bullets: [
          "Every new lead hears back right away",
          "We time the first automatic reply and the first human call apart",
          "We follow up on no-shows and send a reminder before every meeting",
          "A weekly dashboard and review built on cost per meeting held",
        ],
      },
      {
        icon: "phone",
        title: "A live setter on your script",
        bullets: [
          "American setters based in the U.S., never hired overseas. Ascent hires, trains and manages them",
          "They call as you, from a number in your name, on a script your lawyer approved",
          "Up to 20 hours a week, set around when your leads come in",
          "They set up meetings only and never discuss the offering. Breaking that rule stops the work",
          "Every call is recorded for you and your lawyer",
        ],
      },
      {
        icon: "shield",
        title: "Legal checks and firm rules",
        bullets: [
          "Nothing goes live and no one calls until your lawyer approves it in writing",
          "Flat fee only. Nothing is tied to money raised, investors gained or meetings booked",
          "Ascent never checks who is accredited, never touches funds and never gives investment advice",
          "If an approval runs out, calls stop that same day, in writing",
        ],
      },
    ],
    ctaCard: {
      title: "Ready to see what one meeting held costs?",
      body: "Six quick questions. If it's a fit, the calendar is on the next screen.",
      cta: "See if you qualify",
    },
  },

  ctaBand: {
    h2: "Want to know where your last raise's leads went?",
    body: "Thirty minutes on your numbers, in dollars. Bring your lawyer if you like. If it's not a fit, we'll tell you on the call.",
    cta: "Book a call",
  },

  /*
   * The entity block. The definition is the one sentence to be quoted
   * whole; every fact is a practice, a term or a boundary — nothing here
   * is a result.
   */
  // Not rendered on the page since 2026-10-07 (owner's request). The
  // definition still feeds the Organization JSON-LD and llms.txt.
  glance: {
    eyebrow: "ASCENT AT A GLANCE",
    h2: "What Ascent is, in one paragraph.",
    definition:
      "Ascent is a flat-fee investor acquisition firm for U.S. real estate syndicators and private real estate fund sponsors raising under Rule 506(c). It runs counsel-approved paid media on Meta, Google and X, instrumented lead response, and a live, scripted appointment setter who calls every inbound investor lead as the sponsor — and reports one primary number, cost per appointment held. Ascent is not a broker-dealer, finder or placement agent, never verifies accredited status, and takes nothing tied to capital raised.",
    facts: [
      { label: "Serves", value: "U.S. real estate sponsors — multifamily, industrial, self-storage, build-to-rent, opportunity zone, real estate credit" },
      { label: "Offerings", value: "Rule 506(c) and Regulation A+ only. Never 506(b)" },
      { label: "Minimums", value: "$10M+ live raise or an evergreen vehicle; $15K+ monthly media; securities counsel engaged" },
      { label: "Fee model", value: "Flat monthly fee, scaling with media under management. Nothing tied to capital raised" },
      { label: "In writing", value: "A minimum of investor appointments held in 90 days, or Ascent works at no fee until it's met" },
      { label: "Calls", value: "Live, human, scripted, recorded. Inbound leads only. Logistics only — never the offering" },
      { label: "Live in", value: "14 days from account access and counsel's approvals" },
      { label: "Reports", value: "Weekly: speed to first human touch, contact rate, set-to-held rate, cost per appointment held" },
      { label: "Based in", value: "Oklahoma City, Oklahoma. Delivery is remote, nationwide. 100% American owned and operated" },
      { label: "Founder", value: "Caleb Free, Oklahoma City" },
    ],
  },

  guides: {
    eyebrow: "GUIDES",
    h2: "The rules and the math, written down.",
    sub: "What sponsors and their lawyers ask before a call: the SEC rules, checking investors, what investor leads cost and how fees work. No sales pitch. The sources are at the bottom of each guide.",
    indexLabel: "All guides",
  },

  legal: {
    heading: "Legal disclosures",
    paragraphs: [
      "Ascent Client Acquisition Systems LLC provides marketing, lead-response, appointment-setting and reporting services only. Ascent is not a registered broker-dealer, placement agent, finder, investment adviser or funding portal, and does not act in any fiduciary capacity.",
      "Ascent does not offer, sell or distribute securities; does not solicit the purchase or sale of any security; does not make investment recommendations or give investment advice; does not structure, price or negotiate offering terms; does not verify accredited-investor status; and does not handle investor funds or subscription documents. Setters place logistical calls only, under the sponsor's name and on a script approved by the sponsor's securities counsel, and every call is recorded.",
      "Compensation is a flat monthly fee. Ascent does not receive and will not accept any commission, success fee, finder's fee or other transaction-based compensation, including any compensation tied to capital raised, investors introduced or acquired, or appointments booked or held.",
      "Nothing on this site is an offer to sell or a solicitation of an offer to buy any security, nor investment, legal or tax advice. Any offering is made only by the issuer under its own offering documents, under the direction of its counsel, and only to eligible investors in permitted jurisdictions. Benchmark figures on this page are published third-party category figures, are not Ascent results, and do not guarantee any outcome.",
    ],
  },
};

export default sponsors;
