#!/usr/bin/env python3
"""Build the distributable vector logo files in brand/.

The wordmark is emitted as OUTLINES, not <text>, so the files render
identically anywhere -- a print shop, Illustrator, a shirt vendor -- with no
font to install. Outlines come from the same Archivo 800 and IBM Plex Mono 500
woff2 files the site ships, so the vector logo and the website cannot drift.

The chevron geometry is read out of scripts/generate-assets.mjs for the same
reason: one source of truth for the mark.

Requires: pip install fonttools brotli
Run:      python3 scripts/build-logo-svg.py
"""
import json
import pathlib

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAND = ROOT / "brand"
FONTS = ROOT / "src" / "fonts"

ORANGE, INK, WHITE = "#F05E23", "#1F1F1F", "#FFFFFF"

# --- mark geometry, GENERATED by scripts/trace-mark.py ----------------------
_marks = json.loads((ROOT / "brand" / "mark-paths.json").read_text())
MARK_OUTER, MARK_INNER = _marks["outer"], _marks["inner"]
MARK_W, MARK_H = _marks["width"], _marks["height"]

# --- lockup metrics ---------------------------------------------------------
# Measured off the client's Canva lockup export (mark 81.55w x 78.75h units)
# and scaled to this mark's height, so the proportions match the artwork
# rather than being re-invented.
_K = MARK_H / 78.75
GAP = 10.73 * _K        # mark -> wordmark
WORD_CAP = 37.34 * _K   # ASCENT cap height
WORD_BASE = 58.27 * _K  # ASCENT baseline, from the top of the mark
TAG_CAP = 6.72 * _K     # tagline cap height
TAG_BASE = 74.19 * _K   # tagline baseline
TAG_WIDTH_RATIO = 225.08 / 229.14   # tagline measures slightly under ASCENT


def glyph_run(font_path, text):
    """Outlines for `text`, in font units, with cap height and advances."""
    font = TTFont(font_path)
    glyphs, cmap, hmtx = font.getGlyphSet(), font.getBestCmap(), font["hmtx"]
    upem = font["head"].unitsPerEm
    cap = getattr(font["OS/2"], "sCapHeight", None) or int(upem * 0.7)
    run, x = [], 0
    for ch in text:
        name = cmap.get(ord(ch))
        if name is None:
            raise SystemExit(f"no glyph for {ch!r} in {font_path.name}")
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(pen)
        run.append((pen.getCommands(), x))
        x += hmtx[name][0]
    return {"run": run, "width": x, "upem": upem, "cap": cap}


def text_group(spec, cap_target, baseline, x0, fill, tracking=0.0):
    """One <g> of outlined glyphs, scaled to cap_target and flipped y-down."""
    s = cap_target / spec["cap"]
    parts = []
    for i, (d, x) in enumerate(spec["run"]):
        if not d:            # space and other blank glyphs
            continue
        tx = x0 + x * s + tracking * i
        parts.append(
            f'<path transform="translate({tx:.2f} {baseline}) scale({s:.5f} {-s:.5f})" d="{d}"/>'
        )
    return f'<g fill="{fill}">' + "".join(parts) + "</g>", spec["width"] * s


def mark_svg(outer_fill, inner_fill):
    """Two plain filled paths. The transparent channel between the chevrons is
    part of the traced outline, so no mask is needed -- the files drop onto
    Ink, Graphite, a photo, or a garment without carrying a background."""
    return (
        f'<path fill="{outer_fill}" d="{MARK_OUTER}"/>'
        f'<path fill="{inner_fill}" d="{MARK_INNER}"/>'
    )


def svg_doc(width, height, body, title):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.0f} {height:.0f}" '
        f'width="{width:.0f}" height="{height:.0f}" role="img" aria-label="{title}">'
        f"<title>{title}</title>{body}</svg>\n"
    )


def build():
    BRAND.mkdir(exist_ok=True)
    word = glyph_run(FONTS / "archivo-800.woff2", "ASCENT")
    tag = glyph_run(FONTS / "plex-mono-500.woff2", "CLIENT ACQUISITION SYSTEMS")

    word_x = MARK_W + GAP
    word_scale = WORD_CAP / word["cap"]
    word_w = word["width"] * word_scale

    # Letterspace the tagline to the width the delivered lockup uses.
    tag_scale = TAG_CAP / tag["cap"]
    natural = tag["width"] * tag_scale
    tracking = (word_w - natural) / (len(tag["run"]) - 1)

    total_w = word_x + word_w

    for name, outer, inner, wordc, tagc in [
        ("ascent-lockup.svg", ORANGE, INK, INK, ORANGE),
        ("ascent-lockup-white.svg", WHITE, WHITE, WHITE, WHITE),
    ]:
        g_word, _ = text_group(word, WORD_CAP, WORD_BASE, word_x, wordc)
        g_tag, _ = text_group(tag, TAG_CAP, TAG_BASE, word_x, tagc, tracking)
        body = mark_svg(outer, inner) + g_word + g_tag
        (BRAND / name).write_text(
            svg_doc(total_w, MARK_H, body, "Ascent Client Acquisition Systems")
        )
        print(f"wrote brand/{name}  {total_w:.0f}x{MARK_H}")

    for name, outer, inner in [
        ("ascent-mark.svg", ORANGE, INK),
        ("ascent-mark-white.svg", WHITE, WHITE),
    ]:
        (BRAND / name).write_text(
            svg_doc(MARK_W, MARK_H, mark_svg(outer, inner), "Ascent")
        )
        print(f"wrote brand/{name}  {MARK_W}x{MARK_H}")


if __name__ == "__main__":
    build()
